package ass.alfi.mhw.objects;

public enum Skill {
	POISONRESISTANCE("Poison Resistance"),
	PARALYSISRESISTANCE("Paralysis Resistance"),
	SLEEPRESISTANCE("Sleep Resistance"),
	STUNRESISTANCE("Stun Resistance"),
	MUCKRESISTANCE("Muck Resistance"),
	BLASTRESISTANCE("Blast Resistance"),
	BLEEDINGRESISTANCE("Bleeding Resistance"),
	IRONSKIN("Iron Skin"),
	EARPLUGS("Earplugs"),
	WINDPROOF("Windproof"),
	TREMORRESISTANCE("Tremor Resistance"),
	DUNGMASTER("Dungmaster"),
	EFFLUVIALEXPERT("Effluvial Expert"),
	HEATGUARD("Heat Guard"),
	ATTACKBOOST("Attack Boost"),
	DEFENSEBOOST("Defense Boost"),
	HEALTHBOOST("Health Boost"),
	RECOVERYUP("Recovery Up"),
	RECOVERYSPEED("Recovery Speed"),
	FIRERESISTANCE("Fire Resistance"),
	WATERRESISTANCE("Water Resistance"),
	ICERESISTANCE("Ice Resistance"),
	THUNDERRESISTANCE("Thunder Resistance"),
	DRAGONRESISTANCE("Dragon Resistance"),
	BLIGHTRESISTANCE("Blight Resistance"),
	FIREATTACK("Fire Attack"),
	WATERATTACK("Water Attack"),
	ICEATTACK("Ice Attack"),
	THUNDERATTACK("Thunder Attack"),
	DRAGONATTACK("Dragon Attack"),
	POISONATTACK("Poison Attack"),
	PARALYSISATTACK("Paralysis Attack"),
	SLEEPATTACK("Sleep Attack"),
	BLASTATTACK("Blast Attack"),
	NORMALSHOTS("Normal Shots"),
	PIERCINGSHOTS("Piercing Shots"),
	SPREADPOWERSHOTS("Spread/Power Shots"),
	FREEELEMAMMOUP("Free Elem/Ammo Up"),
	CRITICALEYE("Critical Eye"),
	CRITICALBOOST("Critical Boost"),
	WEAKNESSEXPLOIT("Weakness Exploit"),
	FOCUS("Focus"),
	POWERPROLONGER("Power Prolonger"),
	HANDICRAFT("Handicraft"),
	CRITICALDRAW("Critical Draw"),
	PARTBREAKER("Partbreaker"),
	SLUGGER("Slugger"),
	STAMINATHIEF("Stamina Thief"),
	MASTERMOUNTER("Master Mounter"),
	AIRBORNE("Airborne"),
	LATENTPOWER("Latent Power"),
	AGITATOR("Agitator"),
	PEAKPERFORMANCE("Peak Performance"),
	HEROICS("Heroics"),
	FORTIFY("Fortify"),
	RESENTMENT("Resentment"),
	RESUSCITATE("Resuscitate"),
	HORNMAESTRO("Horn Maestro"),
	CAPACITYBOOST("Capacity Boost"),
	SPECIALAMMOBOOST("Special Ammo Boost"),
	ARTILLERY("Artillery"),
	HEAVYARTILLERY("Heavy Artillery"),
	MARATHONRUNNER("Marathon Runner"),
	CONSTITUTION("Constitution"),
	LEAPOFFAITH("Leap of Faith"),
	STAMINASURGE("Stamina Surge"),
	HUNGERRESISTANCE("Hunger Resistance"),
	EVADEWINDOW("Evade Window"),
	EVADEEXTENDER("Evade Extender"),
	GUARD("Guard"),
	QUICKSHEATH("Quick Sheath"),
	WIDERANGE("Wide-Range"),
	ITEMPROLONGER("Item Prolonger"),
	FREEMEAL("Free Meal"),
	SPEEDEATING("Speed Eating"),
	SPEEDSHARPENING("Speed Sharpening"),
	BOMBARDIER("Bombardier"),
	MUSHROOMANCER("Mushroomancer"),
	MASTERFISHER("Master Fisher"),
	PROTRANSPORTER("Pro Transporter"),
	MASTERGATHERER("Master Gatherer"),
	HONEYHUNTER("Honey Hunter"),
	CARVINGPRO("Carving Pro"),
	DIVINEBLESSING("Divine Blessing"),
	PALICORALLY("Palico Rally"),
	BOTANIST("Botanist"),
	GEOLOGIST("Geologist"),
	MAXIMUMMIGHT("Maximum Might"),
	SLINGERCAPACITY("Slinger Capacity"),
	STEALTH("Stealth"),
	FLINCHFREE("Flinch Free"),
	SCOUTFLYRANGEUP("Scoutfly Range Up"),
	SPEEDCRAWLER("Speed Crawler"),
	JUMPMASTER("Jump Master"),
	SPOREPUFFEXPERT("Sporepuff Expert"),
	AQUATICEXPERT("Aquatic Expert"),
	CLIFFHANGER("Cliffhanger"),
	BLINDSIDER("Blindsider"),
	SCHOLAR("Scholar"),
	ENTOMOLOGIST("Entomologist"),
	EFFLUVIARESISTANCE("Effluvia Resistance"),
	SCENTHOUND("Scenthound"),
	FORAGERSLUCK("Forager's Luck"),
	DETECTOR("Detector"),
	BBQMASTER("BBQ Master"),
	TOOLSPECIALIST("Tool Specialist"),
	AFFINITYSLIDING("Affinity Sliding"),
	INTIMIDATOR("Intimidator"),
	HASTENRECOVERY("Hasten Recovery"),
	SUPERRECOVERY("Super Recovery"),
	POISONDURATIONUP("Poison Duration Up"),
	ADRENALINE("Adrenaline"),
	STAMINACAPUP("Stamina Cap Up"),
	CRITICALELEMENT("Critical Element"),
	MINDSEYEBALLISTICS("Mind's Eye/Ballistics"),
	BLUDGEONER("Bludgeoner"),
	NONELEMENTALBOOST("Non-elemental Boost"),
	CAPTUREMASTER("Capture Master"),
	GUARDUP("Guard Up"),
	GUTS("Guts"),
	MASTERSTOUCH("Master's Touch"),
	NULLIFYWINDPRESSURE("Nullify Wind Pressure"),
	RAZORSHARPSPARESHOT("Razor Sharp/Spare Shot"),
	CRITICALSTATUS("Critical Status"),
	GOODLUCK("Good Luck"),
	BOWCHARGEPLUS("Bow Charge Plus"),
	PUNISHINGDRAW("Punishing Draw"),
	PROTECTIVEPOLISH("Protective Polish"),
	POISONFUNCTIONALITY("Poison Functionality"),
	PARAFUNCTIONALITY("Para Functionality"),
	SLEEPFUNCTIONALITY("Sleep Functionality"),
	BLASTFUNCTIONALITY("Blast Functionality"),
	ELDERSEALBOOST("Elderseal Boost");
	
	private String skill;
	
	Skill(String skill) {
		this.skill = skill;
	}
	
	public String getSkill() {
		return skill;
	}
}
